In [95]:
%load_ext autoreload
%autoreload 2
import pandas as pd
%matplotlib inline
import edhec_risk_kit as erk

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [96]:
ind= erk.get_hfi_returns()

In [97]:
erk.var_gaussian(ind["2000":]['Distressed Securities'],level=1)

0.03143017693928047

In [98]:
erk.var_gaussian(ind["2000":]['Distressed Securities'],level=1,modified=True)

0.04966909110627918

In [99]:
erk.var_historic(ind["2000":]["Distressed Securities"],level=1)

0.042642

In [100]:
perf= erk.get_ind_returns()["2013":"2017"]
er=erk.annualize_rets(perf,12)

In [101]:
perf

Food    Beer   Smoke   Games  ...   Rtail   Meals     Fin   Other
2013-01  0.0554  0.0507  0.0561  0.1313  ...  0.0541  0.0523  0.0632  0.0720
2013-02  0.0384  0.0522  0.0221  0.0000  ...  0.0061  0.0070  0.0129  0.0443
2013-03  0.0656  0.0531  0.0272  0.0769  ...  0.0477  0.0550  0.0453  0.0228
2013-04  0.0284  0.0355  0.0440  0.0451  ...  0.0320  0.0240  0.0157  0.0074
2013-05 -0.0345 -0.0147 -0.0298  0.0218  ...  0.0239 -0.0030  0.0708  0.0590
2013-06  0.0084  0.0093 -0.0226 -0.0375  ... -0.0043  0.0161 -0.0043 -0.0113
2013-07  0.0326  0.0273  0.0176  0.0478  ...  0.0639  0.0317  0.0633  0.0434
2013-08 -0.0375 -0.0386 -0.0485  0.0247  ... -0.0486 -0.0229 -0.0419 -0.0381
2013-09  0.0031  0.0134  0.0428  0.0991  ...  0.0443  0.0401  0.0315  0.0296
2013-10  0.0461  0.0625  0.0535  0.0455  ...  0.0539  0.0392  0.0331  0.0364
2013-11  0.0152  0.0115 -0.0242  0.0313  ...  0.0372  0.0320  0.0606  0.0172
2013-12  0.0303 -0.0041  0.0297  0.0702  ...  0.0010 -0.0023  0.0271  0.0282
2014-01 -0.0529 -0.0054 -0.0833 -0.0072  ... -0.0759 -0.0477 -0.0428 -0.0612
2014-02  0.0379  0.0162  0.0335  0.0834  ...  0.0579  0.0484  0.0324  0.0286
2014-03  0.0277  0.0478  0.0407 -0.0544  ... -0.0121  0.0173  0.0239  0.0507
2014-04  0.0122  0.0156  0.0569 -0.0402  ... -0.0084 -0.0123 -0.0348  0.0287
2014-05  0.0415  0.0319  0.0399  0.0280  ...  0.0022  0.0240  0.0181 -0.0043
2014-06  0.0152  0.0285 -0.0117  0.0198  ...  0.0101  0.0253  0.0297 -0.0033
2014-07 -0.0583 -0.0292 -0.0326 -0.0370  ... -0.0178 -0.0311 -0.0208 -0.0207
2014-08  0.0638  0.0546  0.0463 -0.0180  ...  0.0574  0.0332  0.0381  0.0720
2014-09 -0.0053  0.0083  0.0201 -0.0438  ... -0.0151 -0.0060 -0.0059  0.0016
2014-10  0.0170  0.0328  0.0586  0.0058  ...  0.0337  0.0128  0.0387  0.0159
2014-11  0.0568  0.0435  0.0098 -0.0040  ...  0.0896  0.0557  0.0193  0.0456
2014-12 -0.0248 -0.0430 -0.0289 -0.0460  ...  0.0223 -0.0043  0.0207  0.0017
2015-01 -0.0164  0.0090  0.0305  0.0025  ... -0.0024  0.0066 -0.0761 -0.0411
2015-02  0.0444  0.0440  0.0545  0.0587  ...  0.0567  0.0682  0.0793  0.0464
2015-03 -0.0072 -0.0207 -0.0847 -0.0260  ...  0.0101 -0.0029  0.0011 -0.0173
2015-04 -0.0017 -0.0052  0.0602  0.0375  ... -0.0293  0.0051  0.0076 -0.0023
2015-05  0.0203  0.0200  0.0144  0.0071  ...  0.0056  0.0156  0.0309  0.0095
2015-06 -0.0195 -0.0171 -0.0257  0.0130  ... -0.0050  0.0029  0.0134 -0.0357
2015-07  0.0403  0.0351  0.0959  0.0609  ...  0.0584  0.0417  0.0197  0.0319
2015-08 -0.0437 -0.0312 -0.0406 -0.0735  ... -0.0542 -0.0648 -0.0654 -0.0525
2015-09 -0.0119  0.0258  0.0237 -0.0994  ... -0.0172  0.0044 -0.0315 -0.0187
2015-10  0.0581  0.0806  0.1090  0.1461  ...  0.0453  0.0505  0.0590  0.0701
2015-11  0.0011 -0.0071 -0.0300 -0.0041  ...  0.0059 -0.0101  0.0216  0.0006
2015-12  0.0197  0.0031  0.0160 -0.0169  ...  0.0083 -0.0094 -0.0291  0.0031
2016-01 -0.0166 -0.0022  0.0429 -0.0814  ... -0.0447 -0.0093 -0.0962 -0.0321
2016-02  0.0097 -0.0232  0.0095  0.0427  ... -0.0043  0.0105 -0.0283  0.0268
2016-03  0.0471  0.0563  0.0506  0.0863  ...  0.0599  0.0538  0.0667  0.0668
2016-04  0.0064  0.0032 -0.0024 -0.0629  ... -0.0034 -0.0237  0.0397  0.0068
2016-05  0.0207 -0.0090  0.0084  0.0543  ...  0.0122 -0.0147  0.0216 -0.0200
2016-06  0.0477  0.0533  0.0689 -0.0441  ...  0.0076  0.0118 -0.0529  0.0360
2016-07 -0.0049  0.0184 -0.0277  0.0617  ...  0.0385  0.0221  0.0405 -0.0018
2016-08 -0.0050 -0.0088 -0.0120  0.0096  ... -0.0169 -0.0021  0.0490  0.0222
2016-09 -0.0290  0.0165 -0.0276  0.0464  ... -0.0014 -0.0225 -0.0141 -0.0347
2016-10 -0.0031 -0.0163  0.0461  0.0561  ... -0.0355 -0.0192  0.0142 -0.0051
2016-11 -0.0440 -0.0575 -0.0511  0.0388  ...  0.0288  0.0849  0.1285  0.0825
2016-12  0.0446  0.0303  0.0542 -0.0333  ... -0.0095  0.0060  0.0383  0.0255
2017-01  0.0099 -0.0098  0.0565  0.0488  ...  0.0092  0.0075  0.0060 -0.0079
2017-02  0.0175  0.0617  0.0797  0.0069  ...  0.0285  0.0241  0.0462  0.0371
2017-03  0.0055  0.0092  0.0106  0.0582  ...  0.0082  0.0277 -0.0223 -0.0178
2017-04

In [115]:
l=["Books","Steel","Oil","Mines"]
n=er[l].shape[0]

In [116]:
import numpy as np
w_ew= np.repeat(1/n,n)

In [117]:
w_ew

array([0.25, 0.25, 0.25, 0.25])

In [118]:
erk.msr(0.1,er[l],cov.loc[l,l]).max()

0.9999999999999953

In [119]:
erk.msr(0.1,er[l],cov.loc[l,l]).argmax()


1

In [137]:
w_msr=erk.msr(0.1,er[l],cov.loc[l,l])
w_msr

array([4.51375048e-15, 1.00000000e+00, 1.40512602e-16, 0.00000000e+00])

In [121]:
l[1]

'Steel'

In [123]:
w_gmv=erk.gmv(cov.loc[l,l])

In [125]:
w_gmv.max()

0.47702487032166246

In [126]:
w_gmv.argmax()

0

In [127]:
w_gmv

array([4.77024870e-01, 4.33680869e-19, 4.34112024e-01, 8.88631053e-02])

In [128]:
w_gmv[1]

4.336808689942018e-19

In [129]:
ind=erk.get_ind_returns()["2018"]
ind.head()

Food    Beer   Smoke   Games  ...   Rtail   Meals     Fin   Other
2018-01  0.0238 -0.0011  0.0013  0.1726  ...  0.1156  0.0323  0.0611  0.0551
2018-02 -0.0675 -0.0676 -0.0662  0.0109  ... -0.0472 -0.0419 -0.0255 -0.0444
2018-03 -0.0187  0.0127 -0.0165 -0.0017  ... -0.0325 -0.0054 -0.0338 -0.0340
2018-04 -0.0167 -0.0429 -0.1416  0.0331  ...  0.0429  0.0350  0.0118 -0.0190
2018-05 -0.0078 -0.0119 -0.0187  0.0902  ...  0.0136 -0.0195  0.0040 -0.0038

[5 rows x 30 columns]

In [148]:
erk.portfolio_vol(w_gmv,ind[l].cov())*(12**0.5)

0.18973734511535803

In [147]:
erk.portfolio_vol(w_msr,ind[l].cov())*(12**0.5)


0.21983988181484135

In [146]:
ind[l].cov()

Books     Steel       Oil     Mines
Books  0.002799  0.002098  0.002558  0.001629
Steel  0.002098  0.004027  0.003473  0.001843
Oil    0.002558  0.003473  0.005296  0.001961
Mines  0.001629  0.001843  0.001961  0.002059